steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/frontend:$COMMIT_SHA",
        "--build-arg", "VITE_API_URL=${_VITE_API_URL}",
        "--build-arg", "VITE_GCS_BUCKET=${_VITE_GCS_BUCKET}",
        
        "./document-ingestion-pgvector-pipeline/frontend/",
      ]
  
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/frontend:$COMMIT_SHA",
      ]
  
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/frontend:$COMMIT_SHA",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8080"
      ]

options:
  logging: CLOUD_LOGGING_ONLY