steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'document-ingestion-pipeline'
      - '--gen2'
      - '--runtime=python311'
      - '--project=$PROJECT_ID'
      - '--region=$_REGION'
      - '--source=.'
      - '--entry-point=process_document_upload'
      - '--trigger-event-filters=type=google.cloud.storage.object.v1.finalized'
      - '--trigger-event-filters=bucket=$_GCS_BUCKET_NAME'
      - '--set-secrets=DB_INSTANCE=DB_INSTANCE:latest,DB_PASSWORD=DB_PASSWORD:latest' # Reference the secrets
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=$_REGION,DB_NAME=postgres,GCS_BUCKET_NAME=$_GCS_BUCKET_NAME,PUBSUB_TOPIC=document-processing,USE_IAM_AUTH=true'
substitutions:
  _REGION: 'us-central1'
  _GCS_BUCKET_NAME: 'ingestion-docs'

options:
  logging: CLOUD_LOGGING_ONLY
